### ISSUE TITLE
this.adapter.addAll is not a function

### ISSUE THREAD

**Issue by ameensom** [lklepner/socket.io-adapter-mongo#1]
when I try to emit a message i'm getting this error
at Socket.join (/root/autotash-form/node_modules/socket.io/lib/socket.js:248:16)
     at Socket.onconnect (/root/autotash-form/node_modules/socket.io/lib/socket.js:303:8)
     at /root/autotash-form/node_modules/socket.io/lib/namespace.js:175:16
     at _combinedTickCallback (internal/process/next_tick.js:73:7)
     at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by lklepner** [comment]
That stacktrace doesn't contain any references to socket.io-adapter-mongo. 

I'm going to close this issue since it appears to be unrelated
